# Generated by Django 3.2.9 on 2021-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211110_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiyasi', models.CharField(max_length=50)),
                ('ismi', models.CharField(max_length=50)),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('full_text', models.TextField()),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
